version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/aoi"
    versioning-strategy: increase # https://github.com/dependabot/dependabot-core/issues/6446
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/aoi/example"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_aoi"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_aoi/example"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: "/packages/aoi/native"
    schedule:
      interval: weekly
