name: aoi_example
description: aoi example application
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # These two are needed for the example; they are not required by aoi
  collection: ^1.17.0
  http: ^1.0.0

  # You can replace this with the current version of aoi
  aoi: ^0.0.2-dev.1

#  For local testing
#dependency_overrides:
#  aoi:
#    path: ..

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
