name: aoi
description: >
  A Dart/Flutter BLE library based on the multi-platform Rust library btleplug
version: 0.0.2-dev.2
homepage: https://github.com/brookman/aoi
repository: https://github.com/brookman/aoi
issue_tracker: https://github.com/brookman/aoi/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  ffi: ^2.0.1
  flutter_rust_bridge: 2.0.0-dev.36
  freezed_annotation: ^2.2.0
  meta: ^1.8.0

  # TODO https://github.com/fzyzcjy/flutter_rust_bridge/issues/1147
  uuid: ^4.1.0

dev_dependencies:
  build_runner: ^2.3.2
  ffigen: ^11.0.0
  freezed: ^2.2.1
  test: ^1.22.0
