[package]
name = "embedded_aoi"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = { version = "1.82.6", features = ["chrono", "uuid"] }

[dependencies]
anyhow = "1.0.80"
flutter_rust_bridge = { version = "1.82.6", features = ["chrono", "uuid"] }
uuid = "1.7.0"
chrono = "0.4.34"
tokio = { version = "1.36.0", features = ["full"] }
# btleplug = { version = "0.11.5", features = ["serde"] }
btleplug = { git = "https://github.com/brookman/btleplug", features = ["serde"] }
once_cell = "1.19.0"
futures = "0.3.30"
