// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.62.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:collection/collection.dart';

import 'dart:ffi' as ffi;

part 'bridge_generated.freezed.dart';

abstract class Aoi {
  Future<List<AoiAdapter>> getAdaptersStaticMethodAoiAdapter({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetAdaptersStaticMethodAoiAdapterConstMeta;

  Stream<AoiPeripheral> startScanMethodAoiAdapter({required AoiAdapter that, FilterCriteria? filter, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kStartScanMethodAoiAdapterConstMeta;

  Future<void> stopScanMethodAoiAdapter({required AoiAdapter that, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kStopScanMethodAoiAdapterConstMeta;

  Future<AoiConnectedPeripheral> connectMethodAoiPeripheral({required AoiPeripheral that, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kConnectMethodAoiPeripheralConstMeta;

  Future<Uint8List> readMethodAoiConnectedPeripheral(
      {required AoiConnectedPeripheral that, required AoiCharacteristic characteristic, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kReadMethodAoiConnectedPeripheralConstMeta;

  Future<void> writeMethodAoiConnectedPeripheral(
      {required AoiConnectedPeripheral that,
      required AoiCharacteristic characteristic,
      required Uint8List data,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kWriteMethodAoiConnectedPeripheralConstMeta;

  Future<void> writeWithoutResponseMethodAoiConnectedPeripheral(
      {required AoiConnectedPeripheral that,
      required AoiCharacteristic characteristic,
      required Uint8List data,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kWriteWithoutResponseMethodAoiConnectedPeripheralConstMeta;

  Future<void> disconnectMethodAoiConnectedPeripheral({required AoiConnectedPeripheral that, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kDisconnectMethodAoiConnectedPeripheralConstMeta;
}

class AoiAdapter {
  final Aoi bridge;
  final int index;

  AoiAdapter({
    required this.bridge,
    required this.index,
  });

  static Future<List<AoiAdapter>> getAdapters({required Aoi bridge, dynamic hint}) =>
      bridge.getAdaptersStaticMethodAoiAdapter(hint: hint);

  Stream<AoiPeripheral> startScan({FilterCriteria? filter, dynamic hint}) => bridge.startScanMethodAoiAdapter(
        that: this,
        filter: filter,
      );

  Future<void> stopScan({dynamic hint}) => bridge.stopScanMethodAoiAdapter(
        that: this,
      );
}

class AoiCharacteristic {
  final String uuid;
  final String serviceUuid;
  final int propertiesBits;

  AoiCharacteristic({
    required this.uuid,
    required this.serviceUuid,
    required this.propertiesBits,
  });
}

class AoiConnectedPeripheral {
  final Aoi bridge;
  final AoiPeripheral peripheral;
  final List<AoiCharacteristic> characteristics;

  AoiConnectedPeripheral({
    required this.bridge,
    required this.peripheral,
    required this.characteristics,
  });

  Future<Uint8List> read({required AoiCharacteristic characteristic, dynamic hint}) =>
      bridge.readMethodAoiConnectedPeripheral(
        that: this,
        characteristic: characteristic,
      );

  Future<void> write({required AoiCharacteristic characteristic, required Uint8List data, dynamic hint}) =>
      bridge.writeMethodAoiConnectedPeripheral(
        that: this,
        characteristic: characteristic,
        data: data,
      );

  Future<void> writeWithoutResponse(
          {required AoiCharacteristic characteristic, required Uint8List data, dynamic hint}) =>
      bridge.writeWithoutResponseMethodAoiConnectedPeripheral(
        that: this,
        characteristic: characteristic,
        data: data,
      );

  Future<void> disconnect({dynamic hint}) => bridge.disconnectMethodAoiConnectedPeripheral(
        that: this,
      );
}

class AoiManufacturerData {
  final int manufacturerId;
  final Uint8List data;

  AoiManufacturerData({
    required this.manufacturerId,
    required this.data,
  });
}

class AoiPeripheral {
  final Aoi bridge;
  final AoiAdapter adapter;
  final String? name;
  final AoiPeripheralAddress address;
  final List<String> services;
  final List<AoiManufacturerData> manufacturerData;

  AoiPeripheral({
    required this.bridge,
    required this.adapter,
    this.name,
    required this.address,
    required this.services,
    required this.manufacturerData,
  });

  Future<AoiConnectedPeripheral> connect({dynamic hint}) => bridge.connectMethodAoiPeripheral(
        that: this,
      );
}

@freezed
class AoiPeripheralAddress with _$AoiPeripheralAddress {
  const factory AoiPeripheralAddress.macAddress(
    U8Array6 field0,
  ) = AoiPeripheralAddress_MacAddress;
  const factory AoiPeripheralAddress.uuid(
    String field0,
  ) = AoiPeripheralAddress_Uuid;
}

@freezed
class FilterCriteria with _$FilterCriteria {
  const factory FilterCriteria.any(
    List<FilterCriterion> field0,
  ) = FilterCriteria_Any;
  const factory FilterCriteria.all(
    List<FilterCriterion> field0,
  ) = FilterCriteria_All;
}

@freezed
class FilterCriterion with _$FilterCriterion {
  const factory FilterCriterion.hasServiceUuid(
    String field0,
  ) = FilterCriterion_HasServiceUuid;
  const factory FilterCriterion.nameMatchesExactly(
    String field0,
  ) = FilterCriterion_NameMatchesExactly;
  const factory FilterCriterion.nameContains(
    String field0,
  ) = FilterCriterion_NameContains;
  const factory FilterCriterion.manufacturerId(
    int field0,
  ) = FilterCriterion_ManufacturerId;
  const factory FilterCriterion.manufacturerData(
    int field0,
    Uint8List field1,
  ) = FilterCriterion_ManufacturerData;
}

class U8Array6 extends NonGrowableListView<int> {
  static const arraySize = 6;
  U8Array6(Uint8List inner)
      : assert(inner.length == arraySize),
        super(inner);
  U8Array6.unchecked(Uint8List inner) : super(inner);
  U8Array6.init() : super(Uint8List(arraySize));
}

class AoiImpl implements Aoi {
  final AoiPlatform _platform;
  factory AoiImpl(ExternalLibrary dylib) => AoiImpl.raw(AoiPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory AoiImpl.wasm(FutureOr<WasmModule> module) => AoiImpl(module as ExternalLibrary);
  AoiImpl.raw(this._platform);
  Future<List<AoiAdapter>> getAdaptersStaticMethodAoiAdapter({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_get_adapters__static_method__AoiAdapter(port_),
      parseSuccessData: _wire2api_list_aoi_adapter,
      constMeta: kGetAdaptersStaticMethodAoiAdapterConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetAdaptersStaticMethodAoiAdapterConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_adapters__static_method__AoiAdapter",
        argNames: [],
      );

  Stream<AoiPeripheral> startScanMethodAoiAdapter({required AoiAdapter that, FilterCriteria? filter, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_aoi_adapter(that);
    var arg1 = _platform.api2wire_opt_box_autoadd_filter_criteria(filter);
    return _platform.executeStream(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_start_scan__method__AoiAdapter(port_, arg0, arg1),
      parseSuccessData: (d) => _wire2api_aoi_peripheral(d),
      constMeta: kStartScanMethodAoiAdapterConstMeta,
      argValues: [that, filter],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kStartScanMethodAoiAdapterConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "start_scan__method__AoiAdapter",
        argNames: ["that", "filter"],
      );

  Future<void> stopScanMethodAoiAdapter({required AoiAdapter that, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_aoi_adapter(that);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_stop_scan__method__AoiAdapter(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kStopScanMethodAoiAdapterConstMeta,
      argValues: [that],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kStopScanMethodAoiAdapterConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "stop_scan__method__AoiAdapter",
        argNames: ["that"],
      );

  Future<AoiConnectedPeripheral> connectMethodAoiPeripheral({required AoiPeripheral that, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_aoi_peripheral(that);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_connect__method__AoiPeripheral(port_, arg0),
      parseSuccessData: (d) => _wire2api_aoi_connected_peripheral(d),
      constMeta: kConnectMethodAoiPeripheralConstMeta,
      argValues: [that],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kConnectMethodAoiPeripheralConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "connect__method__AoiPeripheral",
        argNames: ["that"],
      );

  Future<Uint8List> readMethodAoiConnectedPeripheral(
      {required AoiConnectedPeripheral that, required AoiCharacteristic characteristic, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_aoi_connected_peripheral(that);
    var arg1 = _platform.api2wire_box_autoadd_aoi_characteristic(characteristic);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_read__method__AoiConnectedPeripheral(port_, arg0, arg1),
      parseSuccessData: _wire2api_uint_8_list,
      constMeta: kReadMethodAoiConnectedPeripheralConstMeta,
      argValues: [that, characteristic],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kReadMethodAoiConnectedPeripheralConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "read__method__AoiConnectedPeripheral",
        argNames: ["that", "characteristic"],
      );

  Future<void> writeMethodAoiConnectedPeripheral(
      {required AoiConnectedPeripheral that,
      required AoiCharacteristic characteristic,
      required Uint8List data,
      dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_aoi_connected_peripheral(that);
    var arg1 = _platform.api2wire_box_autoadd_aoi_characteristic(characteristic);
    var arg2 = _platform.api2wire_uint_8_list(data);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_write__method__AoiConnectedPeripheral(port_, arg0, arg1, arg2),
      parseSuccessData: _wire2api_unit,
      constMeta: kWriteMethodAoiConnectedPeripheralConstMeta,
      argValues: [that, characteristic, data],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kWriteMethodAoiConnectedPeripheralConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "write__method__AoiConnectedPeripheral",
        argNames: ["that", "characteristic", "data"],
      );

  Future<void> writeWithoutResponseMethodAoiConnectedPeripheral(
      {required AoiConnectedPeripheral that,
      required AoiCharacteristic characteristic,
      required Uint8List data,
      dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_aoi_connected_peripheral(that);
    var arg1 = _platform.api2wire_box_autoadd_aoi_characteristic(characteristic);
    var arg2 = _platform.api2wire_uint_8_list(data);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_write_without_response__method__AoiConnectedPeripheral(port_, arg0, arg1, arg2),
      parseSuccessData: _wire2api_unit,
      constMeta: kWriteWithoutResponseMethodAoiConnectedPeripheralConstMeta,
      argValues: [that, characteristic, data],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kWriteWithoutResponseMethodAoiConnectedPeripheralConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "write_without_response__method__AoiConnectedPeripheral",
        argNames: ["that", "characteristic", "data"],
      );

  Future<void> disconnectMethodAoiConnectedPeripheral({required AoiConnectedPeripheral that, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_aoi_connected_peripheral(that);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_disconnect__method__AoiConnectedPeripheral(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kDisconnectMethodAoiConnectedPeripheralConstMeta,
      argValues: [that],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kDisconnectMethodAoiConnectedPeripheralConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "disconnect__method__AoiConnectedPeripheral",
        argNames: ["that"],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  List<String> _wire2api_StringList(dynamic raw) {
    return (raw as List<dynamic>).cast<String>();
  }

  AoiAdapter _wire2api_aoi_adapter(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 1) throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return AoiAdapter(
      bridge: this,
      index: _wire2api_usize(arr[0]),
    );
  }

  AoiCharacteristic _wire2api_aoi_characteristic(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AoiCharacteristic(
      uuid: _wire2api_String(arr[0]),
      serviceUuid: _wire2api_String(arr[1]),
      propertiesBits: _wire2api_u8(arr[2]),
    );
  }

  AoiConnectedPeripheral _wire2api_aoi_connected_peripheral(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AoiConnectedPeripheral(
      bridge: this,
      peripheral: _wire2api_box_aoi_peripheral(arr[0]),
      characteristics: _wire2api_list_aoi_characteristic(arr[1]),
    );
  }

  AoiManufacturerData _wire2api_aoi_manufacturer_data(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AoiManufacturerData(
      manufacturerId: _wire2api_u16(arr[0]),
      data: _wire2api_uint_8_list(arr[1]),
    );
  }

  AoiPeripheral _wire2api_aoi_peripheral(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 5) throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AoiPeripheral(
      bridge: this,
      adapter: _wire2api_box_aoi_adapter(arr[0]),
      name: _wire2api_opt_String(arr[1]),
      address: _wire2api_box_aoi_peripheral_address(arr[2]),
      services: _wire2api_StringList(arr[3]),
      manufacturerData: _wire2api_list_aoi_manufacturer_data(arr[4]),
    );
  }

  AoiPeripheralAddress _wire2api_aoi_peripheral_address(dynamic raw) {
    switch (raw[0]) {
      case 0:
        return AoiPeripheralAddress_MacAddress(
          _wire2api_u8_array_6(raw[1]),
        );
      case 1:
        return AoiPeripheralAddress_Uuid(
          _wire2api_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  AoiAdapter _wire2api_box_aoi_adapter(dynamic raw) {
    return _wire2api_aoi_adapter(raw);
  }

  AoiPeripheral _wire2api_box_aoi_peripheral(dynamic raw) {
    return _wire2api_aoi_peripheral(raw);
  }

  AoiPeripheralAddress _wire2api_box_aoi_peripheral_address(dynamic raw) {
    return _wire2api_aoi_peripheral_address(raw);
  }

  List<AoiAdapter> _wire2api_list_aoi_adapter(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_aoi_adapter).toList();
  }

  List<AoiCharacteristic> _wire2api_list_aoi_characteristic(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_aoi_characteristic).toList();
  }

  List<AoiManufacturerData> _wire2api_list_aoi_manufacturer_data(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_aoi_manufacturer_data).toList();
  }

  String? _wire2api_opt_String(dynamic raw) {
    return raw == null ? null : _wire2api_String(raw);
  }

  int _wire2api_u16(dynamic raw) {
    return raw as int;
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  U8Array6 _wire2api_u8_array_6(dynamic raw) {
    return U8Array6(_wire2api_uint_8_list(raw));
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }

  void _wire2api_unit(dynamic raw) {
    return;
  }

  int _wire2api_usize(dynamic raw) {
    return castInt(raw);
  }
}

// Section: api2wire

@protected
int api2wire_u16(int raw) {
  return raw;
}

@protected
int api2wire_u8(int raw) {
  return raw;
}

@protected
int api2wire_usize(int raw) {
  return raw;
}
// Section: finalizer

class AoiPlatform extends FlutterRustBridgeBase<AoiWire> {
  AoiPlatform(ffi.DynamicLibrary dylib) : super(AoiWire(dylib));

// Section: api2wire

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_String(String raw) {
    return api2wire_uint_8_list(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_StringList> api2wire_StringList(List<String> raw) {
    final ans = inner.new_StringList_0(raw.length);
    for (var i = 0; i < raw.length; i++) {
      ans.ref.ptr[i] = api2wire_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_AoiAdapter> api2wire_box_aoi_adapter(AoiAdapter raw) {
    final ptr = inner.new_box_aoi_adapter_0();
    _api_fill_to_wire_aoi_adapter(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_AoiPeripheral> api2wire_box_aoi_peripheral(AoiPeripheral raw) {
    final ptr = inner.new_box_aoi_peripheral_0();
    _api_fill_to_wire_aoi_peripheral(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_AoiPeripheralAddress> api2wire_box_aoi_peripheral_address(AoiPeripheralAddress raw) {
    final ptr = inner.new_box_aoi_peripheral_address_0();
    _api_fill_to_wire_aoi_peripheral_address(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_AoiAdapter> api2wire_box_autoadd_aoi_adapter(AoiAdapter raw) {
    final ptr = inner.new_box_autoadd_aoi_adapter_0();
    _api_fill_to_wire_aoi_adapter(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_AoiCharacteristic> api2wire_box_autoadd_aoi_characteristic(AoiCharacteristic raw) {
    final ptr = inner.new_box_autoadd_aoi_characteristic_0();
    _api_fill_to_wire_aoi_characteristic(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_AoiConnectedPeripheral> api2wire_box_autoadd_aoi_connected_peripheral(AoiConnectedPeripheral raw) {
    final ptr = inner.new_box_autoadd_aoi_connected_peripheral_0();
    _api_fill_to_wire_aoi_connected_peripheral(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_AoiPeripheral> api2wire_box_autoadd_aoi_peripheral(AoiPeripheral raw) {
    final ptr = inner.new_box_autoadd_aoi_peripheral_0();
    _api_fill_to_wire_aoi_peripheral(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_FilterCriteria> api2wire_box_autoadd_filter_criteria(FilterCriteria raw) {
    final ptr = inner.new_box_autoadd_filter_criteria_0();
    _api_fill_to_wire_filter_criteria(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_list_aoi_characteristic> api2wire_list_aoi_characteristic(List<AoiCharacteristic> raw) {
    final ans = inner.new_list_aoi_characteristic_0(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      _api_fill_to_wire_aoi_characteristic(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_list_aoi_manufacturer_data> api2wire_list_aoi_manufacturer_data(List<AoiManufacturerData> raw) {
    final ans = inner.new_list_aoi_manufacturer_data_0(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      _api_fill_to_wire_aoi_manufacturer_data(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_list_filter_criterion> api2wire_list_filter_criterion(List<FilterCriterion> raw) {
    final ans = inner.new_list_filter_criterion_0(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      _api_fill_to_wire_filter_criterion(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_opt_String(String? raw) {
    return raw == null ? ffi.nullptr : api2wire_String(raw);
  }

  @protected
  ffi.Pointer<wire_FilterCriteria> api2wire_opt_box_autoadd_filter_criteria(FilterCriteria? raw) {
    return raw == null ? ffi.nullptr : api2wire_box_autoadd_filter_criteria(raw);
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_u8_array_6(U8Array6 raw) {
    final ans = inner.new_uint_8_list_0(6);
    ans.ref.ptr.asTypedList(6).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list_0(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

// Section: finalizer

// Section: api_fill_to_wire

  void _api_fill_to_wire_aoi_adapter(AoiAdapter apiObj, wire_AoiAdapter wireObj) {
    wireObj.index = api2wire_usize(apiObj.index);
  }

  void _api_fill_to_wire_aoi_characteristic(AoiCharacteristic apiObj, wire_AoiCharacteristic wireObj) {
    wireObj.uuid = api2wire_String(apiObj.uuid);
    wireObj.service_uuid = api2wire_String(apiObj.serviceUuid);
    wireObj.properties_bits = api2wire_u8(apiObj.propertiesBits);
  }

  void _api_fill_to_wire_aoi_connected_peripheral(AoiConnectedPeripheral apiObj, wire_AoiConnectedPeripheral wireObj) {
    wireObj.peripheral = api2wire_box_aoi_peripheral(apiObj.peripheral);
    wireObj.characteristics = api2wire_list_aoi_characteristic(apiObj.characteristics);
  }

  void _api_fill_to_wire_aoi_manufacturer_data(AoiManufacturerData apiObj, wire_AoiManufacturerData wireObj) {
    wireObj.manufacturer_id = api2wire_u16(apiObj.manufacturerId);
    wireObj.data = api2wire_uint_8_list(apiObj.data);
  }

  void _api_fill_to_wire_aoi_peripheral(AoiPeripheral apiObj, wire_AoiPeripheral wireObj) {
    wireObj.adapter = api2wire_box_aoi_adapter(apiObj.adapter);
    wireObj.name = api2wire_opt_String(apiObj.name);
    wireObj.address = api2wire_box_aoi_peripheral_address(apiObj.address);
    wireObj.services = api2wire_StringList(apiObj.services);
    wireObj.manufacturer_data = api2wire_list_aoi_manufacturer_data(apiObj.manufacturerData);
  }

  void _api_fill_to_wire_aoi_peripheral_address(AoiPeripheralAddress apiObj, wire_AoiPeripheralAddress wireObj) {
    if (apiObj is AoiPeripheralAddress_MacAddress) {
      var pre_field0 = api2wire_u8_array_6(apiObj.field0);
      wireObj.tag = 0;
      wireObj.kind = inner.inflate_AoiPeripheralAddress_MacAddress();
      wireObj.kind.ref.MacAddress.ref.field0 = pre_field0;
      return;
    }
    if (apiObj is AoiPeripheralAddress_Uuid) {
      var pre_field0 = api2wire_String(apiObj.field0);
      wireObj.tag = 1;
      wireObj.kind = inner.inflate_AoiPeripheralAddress_Uuid();
      wireObj.kind.ref.Uuid.ref.field0 = pre_field0;
      return;
    }
  }

  void _api_fill_to_wire_box_aoi_adapter(AoiAdapter apiObj, ffi.Pointer<wire_AoiAdapter> wireObj) {
    _api_fill_to_wire_aoi_adapter(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_aoi_peripheral(AoiPeripheral apiObj, ffi.Pointer<wire_AoiPeripheral> wireObj) {
    _api_fill_to_wire_aoi_peripheral(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_aoi_peripheral_address(
      AoiPeripheralAddress apiObj, ffi.Pointer<wire_AoiPeripheralAddress> wireObj) {
    _api_fill_to_wire_aoi_peripheral_address(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_aoi_adapter(AoiAdapter apiObj, ffi.Pointer<wire_AoiAdapter> wireObj) {
    _api_fill_to_wire_aoi_adapter(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_aoi_characteristic(
      AoiCharacteristic apiObj, ffi.Pointer<wire_AoiCharacteristic> wireObj) {
    _api_fill_to_wire_aoi_characteristic(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_aoi_connected_peripheral(
      AoiConnectedPeripheral apiObj, ffi.Pointer<wire_AoiConnectedPeripheral> wireObj) {
    _api_fill_to_wire_aoi_connected_peripheral(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_aoi_peripheral(AoiPeripheral apiObj, ffi.Pointer<wire_AoiPeripheral> wireObj) {
    _api_fill_to_wire_aoi_peripheral(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_filter_criteria(FilterCriteria apiObj, ffi.Pointer<wire_FilterCriteria> wireObj) {
    _api_fill_to_wire_filter_criteria(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_filter_criteria(FilterCriteria apiObj, wire_FilterCriteria wireObj) {
    if (apiObj is FilterCriteria_Any) {
      var pre_field0 = api2wire_list_filter_criterion(apiObj.field0);
      wireObj.tag = 0;
      wireObj.kind = inner.inflate_FilterCriteria_Any();
      wireObj.kind.ref.Any.ref.field0 = pre_field0;
      return;
    }
    if (apiObj is FilterCriteria_All) {
      var pre_field0 = api2wire_list_filter_criterion(apiObj.field0);
      wireObj.tag = 1;
      wireObj.kind = inner.inflate_FilterCriteria_All();
      wireObj.kind.ref.All.ref.field0 = pre_field0;
      return;
    }
  }

  void _api_fill_to_wire_filter_criterion(FilterCriterion apiObj, wire_FilterCriterion wireObj) {
    if (apiObj is FilterCriterion_HasServiceUuid) {
      var pre_field0 = api2wire_String(apiObj.field0);
      wireObj.tag = 0;
      wireObj.kind = inner.inflate_FilterCriterion_HasServiceUuid();
      wireObj.kind.ref.HasServiceUuid.ref.field0 = pre_field0;
      return;
    }
    if (apiObj is FilterCriterion_NameMatchesExactly) {
      var pre_field0 = api2wire_String(apiObj.field0);
      wireObj.tag = 1;
      wireObj.kind = inner.inflate_FilterCriterion_NameMatchesExactly();
      wireObj.kind.ref.NameMatchesExactly.ref.field0 = pre_field0;
      return;
    }
    if (apiObj is FilterCriterion_NameContains) {
      var pre_field0 = api2wire_String(apiObj.field0);
      wireObj.tag = 2;
      wireObj.kind = inner.inflate_FilterCriterion_NameContains();
      wireObj.kind.ref.NameContains.ref.field0 = pre_field0;
      return;
    }
    if (apiObj is FilterCriterion_ManufacturerId) {
      var pre_field0 = api2wire_u16(apiObj.field0);
      wireObj.tag = 3;
      wireObj.kind = inner.inflate_FilterCriterion_ManufacturerId();
      wireObj.kind.ref.ManufacturerId.ref.field0 = pre_field0;
      return;
    }
    if (apiObj is FilterCriterion_ManufacturerData) {
      var pre_field0 = api2wire_u16(apiObj.field0);
      var pre_field1 = api2wire_uint_8_list(apiObj.field1);
      wireObj.tag = 4;
      wireObj.kind = inner.inflate_FilterCriterion_ManufacturerData();
      wireObj.kind.ref.ManufacturerData.ref.field0 = pre_field0;
      wireObj.kind.ref.ManufacturerData.ref.field1 = pre_field1;
      return;
    }
  }

  void _api_fill_to_wire_opt_box_autoadd_filter_criteria(
      FilterCriteria? apiObj, ffi.Pointer<wire_FilterCriteria> wireObj) {
    if (apiObj != null) _api_fill_to_wire_box_autoadd_filter_criteria(apiObj, wireObj);
  }
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.

/// generated by flutter_rust_bridge
class AoiWire implements FlutterRustBridgeWireBase {
  @internal
  late final dartApi = DartApiDl(init_frb_dart_api_dl);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  AoiWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  AoiWire.fromLookup(ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup) : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>('store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr.asFunction<void Function(DartPostCObjectFnType)>();

  Object get_dart_object(
    int ptr,
  ) {
    return _get_dart_object(
      ptr,
    );
  }

  late final _get_dart_objectPtr = _lookup<ffi.NativeFunction<ffi.Handle Function(ffi.UintPtr)>>('get_dart_object');
  late final _get_dart_object = _get_dart_objectPtr.asFunction<Object Function(int)>();

  void drop_dart_object(
    int ptr,
  ) {
    return _drop_dart_object(
      ptr,
    );
  }

  late final _drop_dart_objectPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>('drop_dart_object');
  late final _drop_dart_object = _drop_dart_objectPtr.asFunction<void Function(int)>();

  int new_dart_opaque(
    Object handle,
  ) {
    return _new_dart_opaque(
      handle,
    );
  }

  late final _new_dart_opaquePtr = _lookup<ffi.NativeFunction<ffi.UintPtr Function(ffi.Handle)>>('new_dart_opaque');
  late final _new_dart_opaque = _new_dart_opaquePtr.asFunction<int Function(Object)>();

  int init_frb_dart_api_dl(
    ffi.Pointer<ffi.Void> obj,
  ) {
    return _init_frb_dart_api_dl(
      obj,
    );
  }

  late final _init_frb_dart_api_dlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>('init_frb_dart_api_dl');
  late final _init_frb_dart_api_dl = _init_frb_dart_api_dlPtr.asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void wire_get_adapters__static_method__AoiAdapter(
    int port_,
  ) {
    return _wire_get_adapters__static_method__AoiAdapter(
      port_,
    );
  }

  late final _wire_get_adapters__static_method__AoiAdapterPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>('wire_get_adapters__static_method__AoiAdapter');
  late final _wire_get_adapters__static_method__AoiAdapter =
      _wire_get_adapters__static_method__AoiAdapterPtr.asFunction<void Function(int)>();

  void wire_start_scan__method__AoiAdapter(
    int port_,
    ffi.Pointer<wire_AoiAdapter> that,
    ffi.Pointer<wire_FilterCriteria> filter,
  ) {
    return _wire_start_scan__method__AoiAdapter(
      port_,
      that,
      filter,
    );
  }

  late final _wire_start_scan__method__AoiAdapterPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_AoiAdapter>,
              ffi.Pointer<wire_FilterCriteria>)>>('wire_start_scan__method__AoiAdapter');
  late final _wire_start_scan__method__AoiAdapter = _wire_start_scan__method__AoiAdapterPtr
      .asFunction<void Function(int, ffi.Pointer<wire_AoiAdapter>, ffi.Pointer<wire_FilterCriteria>)>();

  void wire_stop_scan__method__AoiAdapter(
    int port_,
    ffi.Pointer<wire_AoiAdapter> that,
  ) {
    return _wire_stop_scan__method__AoiAdapter(
      port_,
      that,
    );
  }

  late final _wire_stop_scan__method__AoiAdapterPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_AoiAdapter>)>>(
          'wire_stop_scan__method__AoiAdapter');
  late final _wire_stop_scan__method__AoiAdapter =
      _wire_stop_scan__method__AoiAdapterPtr.asFunction<void Function(int, ffi.Pointer<wire_AoiAdapter>)>();

  void wire_connect__method__AoiPeripheral(
    int port_,
    ffi.Pointer<wire_AoiPeripheral> that,
  ) {
    return _wire_connect__method__AoiPeripheral(
      port_,
      that,
    );
  }

  late final _wire_connect__method__AoiPeripheralPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_AoiPeripheral>)>>(
          'wire_connect__method__AoiPeripheral');
  late final _wire_connect__method__AoiPeripheral =
      _wire_connect__method__AoiPeripheralPtr.asFunction<void Function(int, ffi.Pointer<wire_AoiPeripheral>)>();

  void wire_read__method__AoiConnectedPeripheral(
    int port_,
    ffi.Pointer<wire_AoiConnectedPeripheral> that,
    ffi.Pointer<wire_AoiCharacteristic> characteristic,
  ) {
    return _wire_read__method__AoiConnectedPeripheral(
      port_,
      that,
      characteristic,
    );
  }

  late final _wire_read__method__AoiConnectedPeripheralPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_AoiConnectedPeripheral>,
              ffi.Pointer<wire_AoiCharacteristic>)>>('wire_read__method__AoiConnectedPeripheral');
  late final _wire_read__method__AoiConnectedPeripheral = _wire_read__method__AoiConnectedPeripheralPtr
      .asFunction<void Function(int, ffi.Pointer<wire_AoiConnectedPeripheral>, ffi.Pointer<wire_AoiCharacteristic>)>();

  void wire_write__method__AoiConnectedPeripheral(
    int port_,
    ffi.Pointer<wire_AoiConnectedPeripheral> that,
    ffi.Pointer<wire_AoiCharacteristic> characteristic,
    ffi.Pointer<wire_uint_8_list> data,
  ) {
    return _wire_write__method__AoiConnectedPeripheral(
      port_,
      that,
      characteristic,
      data,
    );
  }

  late final _wire_write__method__AoiConnectedPeripheralPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_AoiConnectedPeripheral>, ffi.Pointer<wire_AoiCharacteristic>,
              ffi.Pointer<wire_uint_8_list>)>>('wire_write__method__AoiConnectedPeripheral');
  late final _wire_write__method__AoiConnectedPeripheral = _wire_write__method__AoiConnectedPeripheralPtr.asFunction<
      void Function(int, ffi.Pointer<wire_AoiConnectedPeripheral>, ffi.Pointer<wire_AoiCharacteristic>,
          ffi.Pointer<wire_uint_8_list>)>();

  void wire_write_without_response__method__AoiConnectedPeripheral(
    int port_,
    ffi.Pointer<wire_AoiConnectedPeripheral> that,
    ffi.Pointer<wire_AoiCharacteristic> characteristic,
    ffi.Pointer<wire_uint_8_list> data,
  ) {
    return _wire_write_without_response__method__AoiConnectedPeripheral(
      port_,
      that,
      characteristic,
      data,
    );
  }

  late final _wire_write_without_response__method__AoiConnectedPeripheralPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_AoiConnectedPeripheral>, ffi.Pointer<wire_AoiCharacteristic>,
              ffi.Pointer<wire_uint_8_list>)>>('wire_write_without_response__method__AoiConnectedPeripheral');
  late final _wire_write_without_response__method__AoiConnectedPeripheral =
      _wire_write_without_response__method__AoiConnectedPeripheralPtr.asFunction<
          void Function(int, ffi.Pointer<wire_AoiConnectedPeripheral>, ffi.Pointer<wire_AoiCharacteristic>,
              ffi.Pointer<wire_uint_8_list>)>();

  void wire_disconnect__method__AoiConnectedPeripheral(
    int port_,
    ffi.Pointer<wire_AoiConnectedPeripheral> that,
  ) {
    return _wire_disconnect__method__AoiConnectedPeripheral(
      port_,
      that,
    );
  }

  late final _wire_disconnect__method__AoiConnectedPeripheralPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_AoiConnectedPeripheral>)>>(
          'wire_disconnect__method__AoiConnectedPeripheral');
  late final _wire_disconnect__method__AoiConnectedPeripheral = _wire_disconnect__method__AoiConnectedPeripheralPtr
      .asFunction<void Function(int, ffi.Pointer<wire_AoiConnectedPeripheral>)>();

  ffi.Pointer<wire_StringList> new_StringList_0(
    int len,
  ) {
    return _new_StringList_0(
      len,
    );
  }

  late final _new_StringList_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_StringList> Function(ffi.Int32)>>('new_StringList_0');
  late final _new_StringList_0 = _new_StringList_0Ptr.asFunction<ffi.Pointer<wire_StringList> Function(int)>();

  ffi.Pointer<wire_AoiAdapter> new_box_aoi_adapter_0() {
    return _new_box_aoi_adapter_0();
  }

  late final _new_box_aoi_adapter_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_AoiAdapter> Function()>>('new_box_aoi_adapter_0');
  late final _new_box_aoi_adapter_0 = _new_box_aoi_adapter_0Ptr.asFunction<ffi.Pointer<wire_AoiAdapter> Function()>();

  ffi.Pointer<wire_AoiPeripheral> new_box_aoi_peripheral_0() {
    return _new_box_aoi_peripheral_0();
  }

  late final _new_box_aoi_peripheral_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_AoiPeripheral> Function()>>('new_box_aoi_peripheral_0');
  late final _new_box_aoi_peripheral_0 =
      _new_box_aoi_peripheral_0Ptr.asFunction<ffi.Pointer<wire_AoiPeripheral> Function()>();

  ffi.Pointer<wire_AoiPeripheralAddress> new_box_aoi_peripheral_address_0() {
    return _new_box_aoi_peripheral_address_0();
  }

  late final _new_box_aoi_peripheral_address_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_AoiPeripheralAddress> Function()>>(
          'new_box_aoi_peripheral_address_0');
  late final _new_box_aoi_peripheral_address_0 =
      _new_box_aoi_peripheral_address_0Ptr.asFunction<ffi.Pointer<wire_AoiPeripheralAddress> Function()>();

  ffi.Pointer<wire_AoiAdapter> new_box_autoadd_aoi_adapter_0() {
    return _new_box_autoadd_aoi_adapter_0();
  }

  late final _new_box_autoadd_aoi_adapter_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_AoiAdapter> Function()>>('new_box_autoadd_aoi_adapter_0');
  late final _new_box_autoadd_aoi_adapter_0 =
      _new_box_autoadd_aoi_adapter_0Ptr.asFunction<ffi.Pointer<wire_AoiAdapter> Function()>();

  ffi.Pointer<wire_AoiCharacteristic> new_box_autoadd_aoi_characteristic_0() {
    return _new_box_autoadd_aoi_characteristic_0();
  }

  late final _new_box_autoadd_aoi_characteristic_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_AoiCharacteristic> Function()>>(
          'new_box_autoadd_aoi_characteristic_0');
  late final _new_box_autoadd_aoi_characteristic_0 =
      _new_box_autoadd_aoi_characteristic_0Ptr.asFunction<ffi.Pointer<wire_AoiCharacteristic> Function()>();

  ffi.Pointer<wire_AoiConnectedPeripheral> new_box_autoadd_aoi_connected_peripheral_0() {
    return _new_box_autoadd_aoi_connected_peripheral_0();
  }

  late final _new_box_autoadd_aoi_connected_peripheral_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_AoiConnectedPeripheral> Function()>>(
          'new_box_autoadd_aoi_connected_peripheral_0');
  late final _new_box_autoadd_aoi_connected_peripheral_0 =
      _new_box_autoadd_aoi_connected_peripheral_0Ptr.asFunction<ffi.Pointer<wire_AoiConnectedPeripheral> Function()>();

  ffi.Pointer<wire_AoiPeripheral> new_box_autoadd_aoi_peripheral_0() {
    return _new_box_autoadd_aoi_peripheral_0();
  }

  late final _new_box_autoadd_aoi_peripheral_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_AoiPeripheral> Function()>>('new_box_autoadd_aoi_peripheral_0');
  late final _new_box_autoadd_aoi_peripheral_0 =
      _new_box_autoadd_aoi_peripheral_0Ptr.asFunction<ffi.Pointer<wire_AoiPeripheral> Function()>();

  ffi.Pointer<wire_FilterCriteria> new_box_autoadd_filter_criteria_0() {
    return _new_box_autoadd_filter_criteria_0();
  }

  late final _new_box_autoadd_filter_criteria_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_FilterCriteria> Function()>>('new_box_autoadd_filter_criteria_0');
  late final _new_box_autoadd_filter_criteria_0 =
      _new_box_autoadd_filter_criteria_0Ptr.asFunction<ffi.Pointer<wire_FilterCriteria> Function()>();

  ffi.Pointer<wire_list_aoi_characteristic> new_list_aoi_characteristic_0(
    int len,
  ) {
    return _new_list_aoi_characteristic_0(
      len,
    );
  }

  late final _new_list_aoi_characteristic_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_list_aoi_characteristic> Function(ffi.Int32)>>(
          'new_list_aoi_characteristic_0');
  late final _new_list_aoi_characteristic_0 =
      _new_list_aoi_characteristic_0Ptr.asFunction<ffi.Pointer<wire_list_aoi_characteristic> Function(int)>();

  ffi.Pointer<wire_list_aoi_manufacturer_data> new_list_aoi_manufacturer_data_0(
    int len,
  ) {
    return _new_list_aoi_manufacturer_data_0(
      len,
    );
  }

  late final _new_list_aoi_manufacturer_data_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_list_aoi_manufacturer_data> Function(ffi.Int32)>>(
          'new_list_aoi_manufacturer_data_0');
  late final _new_list_aoi_manufacturer_data_0 =
      _new_list_aoi_manufacturer_data_0Ptr.asFunction<ffi.Pointer<wire_list_aoi_manufacturer_data> Function(int)>();

  ffi.Pointer<wire_list_filter_criterion> new_list_filter_criterion_0(
    int len,
  ) {
    return _new_list_filter_criterion_0(
      len,
    );
  }

  late final _new_list_filter_criterion_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_list_filter_criterion> Function(ffi.Int32)>>(
          'new_list_filter_criterion_0');
  late final _new_list_filter_criterion_0 =
      _new_list_filter_criterion_0Ptr.asFunction<ffi.Pointer<wire_list_filter_criterion> Function(int)>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list_0(
    int len,
  ) {
    return _new_uint_8_list_0(
      len,
    );
  }

  late final _new_uint_8_list_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_uint_8_list> Function(ffi.Int32)>>('new_uint_8_list_0');
  late final _new_uint_8_list_0 = _new_uint_8_list_0Ptr.asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  ffi.Pointer<AoiPeripheralAddressKind> inflate_AoiPeripheralAddress_MacAddress() {
    return _inflate_AoiPeripheralAddress_MacAddress();
  }

  late final _inflate_AoiPeripheralAddress_MacAddressPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<AoiPeripheralAddressKind> Function()>>(
          'inflate_AoiPeripheralAddress_MacAddress');
  late final _inflate_AoiPeripheralAddress_MacAddress =
      _inflate_AoiPeripheralAddress_MacAddressPtr.asFunction<ffi.Pointer<AoiPeripheralAddressKind> Function()>();

  ffi.Pointer<AoiPeripheralAddressKind> inflate_AoiPeripheralAddress_Uuid() {
    return _inflate_AoiPeripheralAddress_Uuid();
  }

  late final _inflate_AoiPeripheralAddress_UuidPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<AoiPeripheralAddressKind> Function()>>(
          'inflate_AoiPeripheralAddress_Uuid');
  late final _inflate_AoiPeripheralAddress_Uuid =
      _inflate_AoiPeripheralAddress_UuidPtr.asFunction<ffi.Pointer<AoiPeripheralAddressKind> Function()>();

  ffi.Pointer<FilterCriteriaKind> inflate_FilterCriteria_Any() {
    return _inflate_FilterCriteria_Any();
  }

  late final _inflate_FilterCriteria_AnyPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FilterCriteriaKind> Function()>>('inflate_FilterCriteria_Any');
  late final _inflate_FilterCriteria_Any =
      _inflate_FilterCriteria_AnyPtr.asFunction<ffi.Pointer<FilterCriteriaKind> Function()>();

  ffi.Pointer<FilterCriteriaKind> inflate_FilterCriteria_All() {
    return _inflate_FilterCriteria_All();
  }

  late final _inflate_FilterCriteria_AllPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FilterCriteriaKind> Function()>>('inflate_FilterCriteria_All');
  late final _inflate_FilterCriteria_All =
      _inflate_FilterCriteria_AllPtr.asFunction<ffi.Pointer<FilterCriteriaKind> Function()>();

  ffi.Pointer<FilterCriterionKind> inflate_FilterCriterion_HasServiceUuid() {
    return _inflate_FilterCriterion_HasServiceUuid();
  }

  late final _inflate_FilterCriterion_HasServiceUuidPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FilterCriterionKind> Function()>>(
          'inflate_FilterCriterion_HasServiceUuid');
  late final _inflate_FilterCriterion_HasServiceUuid =
      _inflate_FilterCriterion_HasServiceUuidPtr.asFunction<ffi.Pointer<FilterCriterionKind> Function()>();

  ffi.Pointer<FilterCriterionKind> inflate_FilterCriterion_NameMatchesExactly() {
    return _inflate_FilterCriterion_NameMatchesExactly();
  }

  late final _inflate_FilterCriterion_NameMatchesExactlyPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FilterCriterionKind> Function()>>(
          'inflate_FilterCriterion_NameMatchesExactly');
  late final _inflate_FilterCriterion_NameMatchesExactly =
      _inflate_FilterCriterion_NameMatchesExactlyPtr.asFunction<ffi.Pointer<FilterCriterionKind> Function()>();

  ffi.Pointer<FilterCriterionKind> inflate_FilterCriterion_NameContains() {
    return _inflate_FilterCriterion_NameContains();
  }

  late final _inflate_FilterCriterion_NameContainsPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FilterCriterionKind> Function()>>('inflate_FilterCriterion_NameContains');
  late final _inflate_FilterCriterion_NameContains =
      _inflate_FilterCriterion_NameContainsPtr.asFunction<ffi.Pointer<FilterCriterionKind> Function()>();

  ffi.Pointer<FilterCriterionKind> inflate_FilterCriterion_ManufacturerId() {
    return _inflate_FilterCriterion_ManufacturerId();
  }

  late final _inflate_FilterCriterion_ManufacturerIdPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FilterCriterionKind> Function()>>(
          'inflate_FilterCriterion_ManufacturerId');
  late final _inflate_FilterCriterion_ManufacturerId =
      _inflate_FilterCriterion_ManufacturerIdPtr.asFunction<ffi.Pointer<FilterCriterionKind> Function()>();

  ffi.Pointer<FilterCriterionKind> inflate_FilterCriterion_ManufacturerData() {
    return _inflate_FilterCriterion_ManufacturerData();
  }

  late final _inflate_FilterCriterion_ManufacturerDataPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FilterCriterionKind> Function()>>(
          'inflate_FilterCriterion_ManufacturerData');
  late final _inflate_FilterCriterion_ManufacturerData =
      _inflate_FilterCriterion_ManufacturerDataPtr.asFunction<ffi.Pointer<FilterCriterionKind> Function()>();

  void free_WireSyncReturn(
    WireSyncReturn ptr,
  ) {
    return _free_WireSyncReturn(
      ptr,
    );
  }

  late final _free_WireSyncReturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturn)>>('free_WireSyncReturn');
  late final _free_WireSyncReturn = _free_WireSyncReturnPtr.asFunction<void Function(WireSyncReturn)>();
}

class _Dart_Handle extends ffi.Opaque {}

class wire_AoiAdapter extends ffi.Struct {
  @ffi.UintPtr()
  external int index;
}

class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

class wire_FilterCriterion_HasServiceUuid extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> field0;
}

class wire_FilterCriterion_NameMatchesExactly extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> field0;
}

class wire_FilterCriterion_NameContains extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> field0;
}

class wire_FilterCriterion_ManufacturerId extends ffi.Struct {
  @ffi.Uint16()
  external int field0;
}

class wire_FilterCriterion_ManufacturerData extends ffi.Struct {
  @ffi.Uint16()
  external int field0;

  external ffi.Pointer<wire_uint_8_list> field1;
}

class FilterCriterionKind extends ffi.Union {
  external ffi.Pointer<wire_FilterCriterion_HasServiceUuid> HasServiceUuid;

  external ffi.Pointer<wire_FilterCriterion_NameMatchesExactly> NameMatchesExactly;

  external ffi.Pointer<wire_FilterCriterion_NameContains> NameContains;

  external ffi.Pointer<wire_FilterCriterion_ManufacturerId> ManufacturerId;

  external ffi.Pointer<wire_FilterCriterion_ManufacturerData> ManufacturerData;
}

class wire_FilterCriterion extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external ffi.Pointer<FilterCriterionKind> kind;
}

class wire_list_filter_criterion extends ffi.Struct {
  external ffi.Pointer<wire_FilterCriterion> ptr;

  @ffi.Int32()
  external int len;
}

class wire_FilterCriteria_Any extends ffi.Struct {
  external ffi.Pointer<wire_list_filter_criterion> field0;
}

class wire_FilterCriteria_All extends ffi.Struct {
  external ffi.Pointer<wire_list_filter_criterion> field0;
}

class FilterCriteriaKind extends ffi.Union {
  external ffi.Pointer<wire_FilterCriteria_Any> Any;

  external ffi.Pointer<wire_FilterCriteria_All> All;
}

class wire_FilterCriteria extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external ffi.Pointer<FilterCriteriaKind> kind;
}

class wire_AoiPeripheralAddress_MacAddress extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> field0;
}

class wire_AoiPeripheralAddress_Uuid extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> field0;
}

class AoiPeripheralAddressKind extends ffi.Union {
  external ffi.Pointer<wire_AoiPeripheralAddress_MacAddress> MacAddress;

  external ffi.Pointer<wire_AoiPeripheralAddress_Uuid> Uuid;
}

class wire_AoiPeripheralAddress extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external ffi.Pointer<AoiPeripheralAddressKind> kind;
}

class wire_StringList extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_uint_8_list>> ptr;

  @ffi.Int32()
  external int len;
}

class wire_AoiManufacturerData extends ffi.Struct {
  @ffi.Uint16()
  external int manufacturer_id;

  external ffi.Pointer<wire_uint_8_list> data;
}

class wire_list_aoi_manufacturer_data extends ffi.Struct {
  external ffi.Pointer<wire_AoiManufacturerData> ptr;

  @ffi.Int32()
  external int len;
}

class wire_AoiPeripheral extends ffi.Struct {
  external ffi.Pointer<wire_AoiAdapter> adapter;

  external ffi.Pointer<wire_uint_8_list> name;

  external ffi.Pointer<wire_AoiPeripheralAddress> address;

  external ffi.Pointer<wire_StringList> services;

  external ffi.Pointer<wire_list_aoi_manufacturer_data> manufacturer_data;
}

class wire_AoiCharacteristic extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> uuid;

  external ffi.Pointer<wire_uint_8_list> service_uuid;

  @ffi.Uint8()
  external int properties_bits;
}

class wire_list_aoi_characteristic extends ffi.Struct {
  external ffi.Pointer<wire_AoiCharacteristic> ptr;

  @ffi.Int32()
  external int len;
}

class wire_AoiConnectedPeripheral extends ffi.Struct {
  external ffi.Pointer<wire_AoiPeripheral> peripheral;

  external ffi.Pointer<wire_list_aoi_characteristic> characteristics;
}

typedef DartPostCObjectFnType = ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
typedef DartPort = ffi.Int64;
