name: Build & Test

on:
  #pull_request:
  push:
    branches:
      - main

jobs:
  build_apple:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.64.0
          components: rustfmt, clippy

      - name: Build the XCFramework
        run: bash scripts/build-apple.sh

      - name: Upload build artifact (iOS & MacOS)
        uses: actions/upload-artifact@v3
          with:
            name: Aoi.xcframework.zip
            path: platform-build/Aoi.xcframework.zip


  build_windows_linux:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: goto-bus-stop/setup-zig@v2
      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.64.0
          components: rustfmt, clippy

      - name: Build the binaries
        run: bash scripts/build-other.sh

      - name: Upload build artifact (Linux & Windows)
        uses: actions/upload-artifact@v3
          with:
            name: other.tar.gz
            path: platform-build/other.tar.gz